---
- name: Setup for Wordpress
  hosts: wp
  gather_facts: no
  become: yes
#  become_user: root
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present

    - name: install wget
      yum:
        name: wget
        state: present

    - name: install unzip
      yum:
        name: unzip
        state: present

    - name: install yum-utils
      yum:
        name: yum-utils
        state: present


    - name: install remirepo
      yum: 
        name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm 
        state: present

    - name: remirepo
      shell: "{{ item }}"
      with_items:
        - "yum-config-manager --enable remi-php73"

    - name: download wordpress
      get_url: 
        url: http://wordpress.org/latest.zip
        dest: /var/www/html/latest.zip

    - name: unarchive
      unarchive:
        src: /var/www/html/latest.zip
        remote_src: true
        dest: /var/www/html

    - name: directory change    
      shell: "{{ item }}"
      with_items:
        - "cp -R /var/www/html/wordpress/* /var/www/html"

    - name: install php
      yum:
        name: php

    - name: install php-mysql
      yum:
        name: php-mysql

    - name: wp config
      shell: "{{ item }}"
      with_items:
        - "cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php"
        - "sed -i 's/database_name_here/wpDB/g' /var/www/html/wp-config.php"
        - "sed -i 's/username_here/wpuser/g' /var/www/html/wp-config.php"
        - "sed -i 's/password_here/1234/g' /var/www/html/wp-config.php"

    - name: install mysql
      yum:
        name:
        - mariadb-server
        - mysql
        - python3-PyMySQL
        - MySQL-python
        state: present

    - name: Start Mysql Service
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create Application Database
      mysql_db:
        name: "wpDB"
        state: present

    - name: Create Database user
      mysql_user:
        name: "wpuser"
        password: "1234"
        priv: '*.*:ALL'
        state: present
        host: 'localhost'
    - name: ensure apache is running
      service:
        name: httpd
        state: started
